/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBoardRouteImport } from './routes/app.board'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAiRouteImport } from './routes/app.ai'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/app/team',
  path: '/app/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/app/tasks',
  path: '/app/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/app/projects',
  path: '/app/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/app/board',
  path: '/app/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/app/ai',
  path: '/app/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/board': typeof AppBoardRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/board': typeof AppBoardRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/billing': typeof AppBillingRoute
  '/app/board': typeof AppBoardRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/ai'
    | '/app/billing'
    | '/app/board'
    | '/app/dashboard'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/team'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/ai'
    | '/app/billing'
    | '/app/board'
    | '/app/dashboard'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/team'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/app/ai'
    | '/app/billing'
    | '/app/board'
    | '/app/dashboard'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/team'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  AppAiRoute: typeof AppAiRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBoardRoute: typeof AppBoardRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team': {
      id: '/app/team'
      path: '/app/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/app/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/app/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/board': {
      id: '/app/board'
      path: '/app/board'
      fullPath: '/app/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/app/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  AppAiRoute: AppAiRoute,
  AppBillingRoute: AppBillingRoute,
  AppBoardRoute: AppBoardRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
